### ISSUE TITLE
Error: `git push -u origin main` vs `master`

### ISSUE THREAD

**Issue by hermionexyz** [githubtraining/uploading-your-local-project#28]
## Bug Report

**Current behavior**
Using the command line, step five creates an error:

> 5. Type `git push -u origin main` to push the files you have locally to the remote on GitHub. (You may be asked to log in.)

The result is:
```
error: src refspec main does not match any
error: failed to push some refs to 'https://github.com/hermionexyz/github-upload.git'
```

**Possible solution**
This works instead:
```
git push -u origin master
```

**Additional context**
I guessed this solution after seeing this [StackExchange answer](https://stackoverflow.com/questions/24114676/git-error-failed-to-push-some-refs-to-remote/24114760#24114760) using `master` instead of `main`. The answer says `master` was deprecated in 10-2020, so I'm guessing this tutorial hasn't been updated.

**Comment by brianamarie** [comment]
Hello @hermionexyz 👋🏻 Thank you for opening this issue!

We have updated this course to use `main` instead of `master` as the default branch for the instructions. This is part of a broader motion. The default branch name for new repositories created on GitHub is now main. 

The behavior you encountered would be expected if a user setting has an alternative default branch name. This can be updated [in your user account settings](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/managing-the-default-branch-name-for-your-repositories).

To read more, see this [/renaming](https://github.com/github/renaming) repository with a lot more context and information. 😊
